### ISSUE TITLE
没部署成功，无法登录，日志也输出不详细，最好能弄debug最好了。

### ISSUE THREAD

**Issue by 786951355** [icyxp/kubernetes-dashboard-ldap#1]
部署文档写的有点凌乱，特别是LDAP那段，secret.sh脚本在格式化的时候有问题，之前获取的值写入token和ca.crt的换行有问题

**Comment by icyxp** [comment]
LDAP 你那里不明白？

**Comment by ZhangSIming-blyq** [comment]
> LDAP 你那里不明白？

secret.sh部分建议改为:

```shell
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: k8s-mutiboard-ldap-cert
  namespace: kube-system
  labels:
    app: k8s-mutiboard-ldap
type: Opaque
data:
  local_token: $(openssl base64 -in ./token/cluster1/token -A)
  local_ca.crt: $(openssl base64 -in ./token/cluster1/ca.crt -A)
EOF
```

**Comment by icyxp** [comment]
感谢，已采纳

**Comment by icyxp** [comment]
Debug mode is supported, add `debug: true` in configmap.yaml

**Comment by 786951355** [comment]
`  baseDN: dc=corp,dc=patsnap,dc=com
  filter: (&(objectClass=person)(sAMAccountName=%s))
  attributes: user_dn
  orgUnitName: OU=`
我这里是windows的AD，我的DN是 cn=ldapadmin,ou=it,ou=功能,dc=example,dc=com,这里面怎么对应上呢？

**Comment by icyxp** [comment]
`
my configmap
baseDN: dc=corp,dc=icyboy,dc=com
filter: (&(objectClass=person)(sAMAccountName=%s))
attributes: user_dn
orgUnitName: OU=

log：
2020/11/20 16:42:44 >>>>>>>>>>>>>>>>>>>>>>>>>> Distinguished Name: CN=Peng Xu,OU=DevOps team,OU=icyboySZ,OU=icyboy,DC=corp,DC=icyboy,DC=com <<<<<<<<<<<<<<<<<<<<<<<<
2020/11/20 16:42:44 >>>>>>>>>>>>>>>>>>>>>>>>>> Group Name: DevOps team <<<<<<<<<<<<<<<<<<<<<<<<
`

you can see your `Distinguished Name` print what， and i get first OU `[DevOps team]` as group

**Comment by 786951355** [comment]
```
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

panic: html/template: pattern matches no files: `templates/*.tmpl`

goroutine 1 [running]:
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc000343a40, 0x144a3b9, 0x10)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:185 +0x362
main.initRouter(0x50, 0x0)
	/go/src/dashboard-ldap/router.go:26 +0x10f
main.main()
	/go/src/dashboard-ldap/main.go:34 +0x34

```
是不是少了什么。

**Comment by 786951355** [comment]
```
2020/11/23 14:47:17 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /admin/                   --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/cmdline            --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/profile            --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] POST   /admin/symbol             --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/symbol             --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/trace              --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/allocs             --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/block              --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/goroutine          --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/heap               --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/mutex              --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /admin/threadcreate       --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
panic: html/template: pattern matches no files: `templates/*.tmpl`

goroutine 1 [running]:
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc0003f8000, 0x14af2d5, 0x10)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:185 +0x362
main.initRouter(0x50, 0xc000422410)
	/go/src/dashboard-ldap/router.go:36 +0x16b
main.main()
	/go/src/dashboard-ldap/main.go:27 +0x34
```
用的镜像是2.0.0的

**Comment by icyxp** [comment]
Sorry！try again！！you open `debug` mode，there are some errors referencing static resources，you need pull 2.0.0 again！

**Comment by 786951355** [comment]
就是2.0.0的镜像。
![Uploading image.png…]()

**Comment by 786951355** [comment]
```
image: icyboy/k8s-mutiboard-ldap:2.0.0
```

**Comment by icyxp** [comment]
you need `docker rmi icyboy/k8s-mutiboard-ldap:2.0.0 && docker pull icyboy/k8s-mutiboard-ldap:2.0.0` again

**Comment by icyxp** [comment]
Any update?I will close this question.

**Comment by 786951355** [comment]
关闭吧，不折腾了，没成功。
